title: Taxonomy As A Service
description: Controlled Vocabularies and Taxonomies for Humanitarians
baseurl: '/taas-data' # the subpath of your site, e.g. /blog
url: 'https://rupl.github.io' # the base hostname & protocol for your site, e.g. http://example.com
email: ocha-vocabulary@un.org

collections:
  - vocabs

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - .vendor
  - .bundle
  - package.json
  - gulpfile.js
  - css/styles.scss
  - README.md
